### ISSUE TITLE
Support file globbing patterns

### ISSUE THREAD

**Issue by Mottie** [sindresorhus/grunt-strip-json-comments#2]
In an attempt to use this plugin on multiple files, I could not get any of the file formats or [globbing patterns](http://gruntjs.com/configuring-tasks#globbing-patterns) to work - I only see errors.

> Running "stripJsonComments:src" (stripJsonComments) task
Warning: Unable to read "src/a.js,src/b.js,src/c.js" file (Error code: ENOENT). Use --force to continue.

Am I missing something?

I'm not familiar with Grunt plugins, so I wouldn't know what changes were needed to submit a PR.

**Comment by sindresorhus** [comment]
See: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

You need to set `expand: true`.
